language: go

go:
    - 1.8
    - 1.9

install:
  - go get -t ./...
  - make install-linters

script:
  - make check

notifications:
  email:
    - travis@skycoin.net
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
